#[derive(Clone)]
#[derive(Copy)]
#[derive(Default)]
pub enum RsgColor {
    #[default]
    None,
    Name,
AliceBlue,
Aliceblue,
AntiqueWhite,
Antiquewhite,
Antiquewhite1,
Antiquewhite2,
Antiquewhite3,
Antiquewhite4,
Agua,
Aquamarine,
Aquamarine1,
Aquamarine2,
Aquamarine3,
Aquamarine4,
Azure,
Azure1,
Azure2,
Azure3,
Azure4,
Beige,
Bisque,
Bisque1,
Bisque2,
Bisque3,
Bisque4,
Black,
BlanchedAlmond,
Blanchedalmond,
Blue,
BlueViolet,
Blue1,
Blue2,
Blue3,
Blue4,
Blueviolet,
Brown,
Brown1,
Brown2,
Brown3,
Brown4,
Burlywood,
Burlywood1,
Burlywood2,
Burlywood3,
Burlywood4,
CadetBlue,
Cadetblue,
Cadetblue1,
Cadetblue2,
Cadetblue3,
Cadetblue4,
Chartreuse,
Chartreuse1,
Chartreuse2,
Chartreuse3,
Chartreuse4,
Chocolate,
Chocolate1,
Chocolate2,
Chocolate3,
Chocolate4,
Coral,
Coral1,
Coral2,
Coral3,
Coral4,
CornflowerBlue,
Cornflowerblue,
Cornsilk,
Cornsilk1,
Cornsilk2,
Cornsilk3,
Cornsilk4,
Crymson,
Cyan,
Cyan1,
Cyan2,
Cyan3,
Cyan4,
DarkBlue,
DarkCyan,
DarkGoldenrod,
DarkGray,
DarkGreen,
DarkGrey,
DarkKhaki,
DarkMagenta,
DarkOliveGreen,
DarkOrange,
DarkOrchid,
DarkRed,
DarkSalmon,
DarkSeaGreen,
DarkSlateBlue,
DarkSlateGray,
DarkSlateGrey,
DarkTurquoise,
DarkViolet,
Darkblue,
Darkcyan,
Darkgoldenrod,
Darkgoldenrod1,
Darkgoldenrod2,
Darkgoldenrod3,
Darkgoldenrod4,
Darkgray,
Darkgreen,
Darkgrey,
Darkkhaki,
Darkmagenta,
Darkolivegreen,
Darkolivegreen1,
Darkolivegreen2,
Darkolivegreen3,
Darkolivegreen4,
Darkorange,
Darkorange1,
Darkorange2,
Darkorange3,
Darkorange4,
Darkorchid,
Darkorchid1,
Darkorchid2,
Darkorchid3,
Darkorchid4,
Darkred,
Darksalmon,
Darkseagreen,
Darkseagreen1,
Darkseagreen2,
Darkseagreen3,
Darkseagreen4,
Darkslateblue,
Darkslategray,
Darkslategray1,
Darkslategray2,
Darkslategray3,
Darkslategray4,
Darkslategrey,
Darkturquoise,
Darkviolet,
DeepPink,
DeepSkyBlue,
Deeppink,
Deeppink1,
Deeppink2,
Deeppink3,
Deeppink4,
Deepskyblue,
Deepskyblue1,
Deepskyblue2,
Deepskyblue3,
Deepskyblue4,
DimGray,
DimGrey,
Dimgray,
Dimgrey,
DodgerBlue,
Dodgerblue,
Dodgerblue1,
Dodgerblue2,
Dodgerblue3,
Dodgerblue4,
Firebrick,
Firebrick1,
Firebrick2,
Firebrick3,
Firebrick4,
FloralWhite,
Floralwhite,
ForestGreen,
Forestgreen,
Fuchsia,
Gainsboro,
GhostWhite,
Ghostwhite,
Gold,
Gold1,
Gold2,
Gold3,
Gold4,
Goldenrod,
Goldenrod1,
Goldenrod2,
Goldenrod3,
Goldenrod4,
Gray,
Gray0,
Gray1,
Gray2,
Gray3,
Gray4,
Gray5,
Gray6,
Gray7,
Gray8,
Gray9,
Gray10,
Gray11,
Gray12,
Gray13,
Gray14,
Gray15,
Gray16,
Gray17,
Gray18,
Gray19,
Gray20,
Gray21,
Gray22,
Gray23,
Gray24,
Gray25,
Gray26,
Gray27,
Gray28,
Gray29,
Gray30,
Gray31,
Gray32,
Gray33,
Gray34,
Gray35,
Gray36,
Gray37,
Gray38,
Gray39,
Gray40,
Gray41,
Gray42,
Gray43,
Gray44,
Gray45,
Gray46,
Gray47,
Gray48,
Gray49,
Gray50,
Gray51,
Gray52,
Gray53,
Gray54,
Gray55,
Gray56,
Gray57,
Gray58,
Gray59,
Gray60,
Gray61,
Gray62,
Gray63,
Gray64,
Gray65,
Gray66,
Gray67,
Gray68,
Gray69,
Gray70,
Gray71,
Gray72,
Gray73,
Gray74,
Gray75,
Gray76,
Gray77,
Gray78,
Gray79,
Gray80,
Gray81,
Gray82,
Gray83,
Gray84,
Gray85,
Gray86,
Gray87,
Gray88,
Gray89,
Gray90,
Gray91,
Gray92,
Gray93,
Gray94,
Gray95,
Gray96,
Gray97,
Gray98,
Gray99,
Gray100,
Green,
GreenYellow,
Green1,
Green2,
Green3,
Green4,
Greenyellow,
Grey,
Grey0,
Grey1,
Grey2,
Grey3,
Grey4,
Grey5,
Grey6,
Grey7,
Grey8,
Grey9,
Grey10,
Grey11,
Grey12,
Grey13,
Grey14,
Grey15,
Grey16,
Grey17,
Grey18,
Grey19,
Grey20,
Grey21,
Grey22,
Grey23,
Grey24,
Grey25,
Grey26,
Grey27,
Grey28,
Grey29,
Grey30,
Grey31,
Grey32,
Grey33,
Grey34,
Grey35,
Grey36,
Grey37,
Grey38,
Grey39,
Grey40,
Grey41,
Grey42,
Grey43,
Grey44,
Grey45,
Grey46,
Grey47,
Grey48,
Grey49,
Grey50,
Grey51,
Grey52,
Grey53,
Grey54,
Grey55,
Grey56,
Grey57,
Grey58,
Grey59,
Grey60,
Grey61,
Grey62,
Grey63,
Grey64,
Grey65,
Grey66,
Grey67,
Grey68,
Grey69,
Grey70,
Grey71,
Grey72,
Grey73,
Grey74,
Grey75,
Grey76,
Grey77,
Grey78,
Grey79,
Grey80,
Grey81,
Grey82,
Grey83,
Grey84,
Grey85,
Grey86,
Grey87,
Grey88,
Grey89,
Grey90,
Grey91,
Grey92,
Grey93,
Grey94,
Grey95,
Grey96,
Grey97,
Grey98,
Grey99,
Grey100,
Honeydew,
Honeydew1,
Honeydew2,
Honeydew3,
Honeydew4,
HotPink,
Hotpink,
Hotpink1,
Hotpink2,
Hotpink3,
Hotpink4,
IndianRed,
Indianred,
Indianred1,
Indianred2,
Indianred3,
Indianred4,
Indigo,
Ivory,
Ivory1,
Ivory2,
Ivory3,
Ivory4,
Khaki,
Khaki1,
Khaki2,
Khaki3,
Khaki4,
Lavender,
LavenderBlush,
Lavenderblush,
Lavenderblush1,
Lavenderblush2,
Lavenderblush3,
Lavenderblush4,
LawnGreen,
Lawngreen,
LemonChiffon,
Lemonchiffon,
Lemonchiffon1,
Lemonchiffon2,
Lemonchiffon3,
Lemonchiffon4,
LightBlue,
LightCoral,
LightCyan,
LightGoldenrod,
LightGoldenrodYellow,
LightGray,
LightGreen,
LightGrey,
LightPink,
LightSalmon,
LightSeaGreen,
LightSkyBlue,
LightSlateBlue,
LightSlateGray,
LightSlateGrey,
LightSteelBlue,
LightYellow,
Lightblue,
Lightblue1,
Lightblue2,
Lightblue3,
Lightblue4,
Lightcoral,
Lightcyan,
Lightcyan1,
Lightcyan2,
Lightcyan3,
Lightcyan4,
Lightgoldenrod,
Lightgoldenrod1,
Lightgoldenrod2,
Lightgoldenrod3,
Lightgoldenrod4,
Lightgoldenrodyellow,
Lightgray,
Lightgreen,
Lightgrey,
Lightpink,
Lightpink1,
Lightpink2,
Lightpink3,
Lightpink4,
Lightsalmon,
Lightsalmon1,
Lightsalmon2,
Lightsalmon3,
Lightsalmon4,
Lightseagreen,
Lightskyblue,
Lightskyblue1,
Lightskyblue2,
Lightskyblue3,
Lightskyblue4,
Lightslateblue,
Lightslategray,
Lightslategrey,
Lightsteelblue,
Lightsteelblue1,
Lightsteelblue2,
Lightsteelblue3,
Lightsteelblue4,
Lightyellow,
Lightyellow1,
Lightyellow2,
Lightyellow3,
Lightyellow4,
Lime,
LimeGreen,
Limegreen,
Linen,
Magenta,
Magenta1,
Magenta2,
Magenta3,
Magenta4,
Maroon,
Maroon1,
Maroon2,
Maroon3,
Maroon4,
MediumAquamarine,
MediumBlue,
MediumOrchid,
MediumPurple,
MediumSeaGreen,
MediumSlateBlue,
MediumSpringGreen,
MediumTurquoise,
MediumVioletRed,
Mediumaquamarine,
Mediumblue,
Mediumorchid,
Mediumorchid1,
Mediumorchid2,
Mediumorchid3,
Mediumorchid4,
Mediumpurple,
Mediumpurple1,
Mediumpurple2,
Mediumpurple3,
Mediumpurple4,
Mediumseagreen,
Mediumslateblue,
Mediumspringgreen,
Mediumturquoise,
Mediumvioletred,
MidnightBlue,
Midnightblue,
MintCream,
Mintcream,
MistyRose,
Mistyrose,
Mistyrose1,
Mistyrose2,
Mistyrose3,
Mistyrose4,
Moccasin,
NavajoWhite,
Navajowhite,
Navajowhite1,
Navajowhite2,
Navajowhite3,
Navajowhite4,
Navy,
NavyBlue,
Navyblue,
OldLace,
Oldlace,
Olive,
OliveDrab,
Olivedrab,
Olivedrab1,
Olivedrab2,
Olivedrab3,
Olivedrab4,
Orange,
OrangeRed,
Orange1,
Orange2,
Orange3,
Orange4,
Orangered,
Orangered1,
Orangered2,
Orangered3,
Orangered4,
Orchid,
Orchid1,
Orchid2,
Orchid3,
Orchid4,
PaleGoldenrod,
PaleGreen,
PaleTurquoise,
PaleVioletRed,
Palegoldenrod,
Palegreen,
Palegreen1,
Palegreen2,
Palegreen3,
Palegreen4,
Paleturquoise,
Paleturquoise1,
Paleturquoise2,
Paleturquoise3,
Paleturquoise4,
Palevioletred,
Palevioletred1,
Palevioletred2,
Palevioletred3,
Palevioletred4,
PapayaWhip,
Papayawhip,
PeachPuff,
Peachpuff,
Peachpuff1,
Peachpuff2,
Peachpuff3,
Peachpuff4,
Peru,
Pink,
Pink1,
Pink2,
Pink3,
Pink4,
Plum,
Plum1,
Plum2,
Plum3,
Plum4,
PowderBlue,
Powderblue,
Purple,
Purple1,
Purple2,
Purple3,
Purple4,
Red,
Red1,
Red2,
Red3,
Red4,
RosyBrown,
Rosybrown,
Rosybrown1,
Rosybrown2,
Rosybrown3,
Rosybrown4,
RoyalBlue,
Royalblue,
Royalblue1,
Royalblue2,
Royalblue3,
Royalblue4,
SaddleBrown,
Saddlebrown,
Salmon,
Salmon1,
Salmon2,
Salmon3,
Salmon4,
SandyBrown,
Sandybrown,
SeaGreen,
Seagreen,
Seagreen1,
Seagreen2,
Seagreen3,
Seagreen4,
Seashell,
Seashell1,
Seashell2,
Seashell3,
Seashell4,
Sienna,
Sienna1,
Sienna2,
Sienna3,
Sienna4,
Silver,
SkyBlue,
Skyblue,
Skyblue1,
Skyblue2,
Skyblue3,
Skyblue4,
SlateBlue,
SlateGray,
SlateGrey,
Slateblue,
Slateblue1,
Slateblue2,
Slateblue3,
Slateblue4,
Slategray,
Slategray1,
Slategray2,
Slategray3,
Slategray4,
Slategrey,
Snow,
Snow1,
Snow2,
Snow3,
Snow4,
SpringGreen,
Springgreen,
Springgreen1,
Springgreen2,
Springgreen3,
Springgreen4,
SteelBlue,
Steelblue,
Steelblue1,
Steelblue2,
Steelblue3,
Steelblue4,
Tan,
Tan1,
Tan2,
Tan3,
Tan4,
Teal,
Thistle,
Thistle1,
Thistle2,
Thistle3,
Thistle4,
Tomato,
Tomato1,
Tomato2,
Tomato3,
Tomato4,
Turquoise,
Turquoise1,
Turquoise2,
Turquoise3,
Turquoise4,
Violet,
VioletRed,
Violetred,
Violetred1,
Violetred2,
Violetred3,
Violetred4,
Wheat,
Wheat1,
Wheat2,
Wheat3,
Wheat4,
White,
WhiteSmoke,
Whitesmoke,
Yellow,
YellowGreen,
Yellow1,
Yellow2,
Yellow3,
Yellow4,
Yellowgreen,
}

pub fn get_rsg_color(which: RsgColor) -> String {
    match which {
        RsgColor::Name => return String::from("Name"),
RsgColor::Red => return String::from("Red"),
RsgColor::Green => return String::from("Green"),
RsgColor::Blue => return String::from("Blue"),
RsgColor::AliceBlue => return String::from("alice blue"),
RsgColor::Aliceblue => return String::from("AliceBlue"),
RsgColor::AntiqueWhite => return String::from("antique white"),
RsgColor::Antiquewhite => return String::from("AntiqueWhite"),
RsgColor::Antiquewhite1 => return String::from("AntiqueWhite1"),
RsgColor::Antiquewhite2 => return String::from("AntiqueWhite2"),
RsgColor::Antiquewhite3 => return String::from("AntiqueWhite3"),
RsgColor::Antiquewhite4 => return String::from("AntiqueWhite4"),
RsgColor::Agua => return String::from("agua"),
RsgColor::Aquamarine => return String::from("aquamarine"),
RsgColor::Aquamarine1 => return String::from("aquamarine1"),
RsgColor::Aquamarine2 => return String::from("aquamarine2"),
RsgColor::Aquamarine3 => return String::from("aquamarine3"),
RsgColor::Aquamarine4 => return String::from("aquamarine4"),
RsgColor::Azure => return String::from("azure"),
RsgColor::Azure1 => return String::from("azure1"),
RsgColor::Azure2 => return String::from("azure2"),
RsgColor::Azure3 => return String::from("azure3"),
RsgColor::Azure4 => return String::from("azure4"),
RsgColor::Beige => return String::from("beige"),
RsgColor::Bisque => return String::from("bisque"),
RsgColor::Bisque1 => return String::from("bisque1"),
RsgColor::Bisque2 => return String::from("bisque2"),
RsgColor::Bisque3 => return String::from("bisque3"),
RsgColor::Bisque4 => return String::from("bisque4"),
RsgColor::Black => return String::from("black"),
RsgColor::BlanchedAlmond => return String::from("blanched almond"),
RsgColor::Blanchedalmond => return String::from("BlanchedAlmond"),
RsgColor::Blue => return String::from("blue"),
RsgColor::BlueViolet => return String::from("blue violet"),
RsgColor::Blue1 => return String::from("blue1"),
RsgColor::Blue2 => return String::from("blue2"),
RsgColor::Blue3 => return String::from("blue3"),
RsgColor::Blue4 => return String::from("blue4"),
RsgColor::Blueviolet => return String::from("BlueViolet"),
RsgColor::Brown => return String::from("brown"),
RsgColor::Brown1 => return String::from("brown1"),
RsgColor::Brown2 => return String::from("brown2"),
RsgColor::Brown3 => return String::from("brown3"),
RsgColor::Brown4 => return String::from("brown4"),
RsgColor::Burlywood => return String::from("burlywood"),
RsgColor::Burlywood1 => return String::from("burlywood1"),
RsgColor::Burlywood2 => return String::from("burlywood2"),
RsgColor::Burlywood3 => return String::from("burlywood3"),
RsgColor::Burlywood4 => return String::from("burlywood4"),
RsgColor::CadetBlue => return String::from("cadet blue"),
RsgColor::Cadetblue => return String::from("CadetBlue"),
RsgColor::Cadetblue1 => return String::from("CadetBlue1"),
RsgColor::Cadetblue2 => return String::from("CadetBlue2"),
RsgColor::Cadetblue3 => return String::from("CadetBlue3"),
RsgColor::Cadetblue4 => return String::from("CadetBlue4"),
RsgColor::Chartreuse => return String::from("chartreuse"),
RsgColor::Chartreuse1 => return String::from("chartreuse1"),
RsgColor::Chartreuse2 => return String::from("chartreuse2"),
RsgColor::Chartreuse3 => return String::from("chartreuse3"),
RsgColor::Chartreuse4 => return String::from("chartreuse4"),
RsgColor::Chocolate => return String::from("chocolate"),
RsgColor::Chocolate1 => return String::from("chocolate1"),
RsgColor::Chocolate2 => return String::from("chocolate2"),
RsgColor::Chocolate3 => return String::from("chocolate3"),
RsgColor::Chocolate4 => return String::from("chocolate4"),
RsgColor::Coral => return String::from("coral"),
RsgColor::Coral1 => return String::from("coral1"),
RsgColor::Coral2 => return String::from("coral2"),
RsgColor::Coral3 => return String::from("coral3"),
RsgColor::Coral4 => return String::from("coral4"),
RsgColor::CornflowerBlue => return String::from("cornflower blue"),
RsgColor::Cornflowerblue => return String::from("CornflowerBlue"),
RsgColor::Cornsilk => return String::from("cornsilk"),
RsgColor::Cornsilk1 => return String::from("cornsilk1"),
RsgColor::Cornsilk2 => return String::from("cornsilk2"),
RsgColor::Cornsilk3 => return String::from("cornsilk3"),
RsgColor::Cornsilk4 => return String::from("cornsilk4"),
RsgColor::Crymson => return String::from("crymson"),
RsgColor::Cyan => return String::from("cyan"),
RsgColor::Cyan1 => return String::from("cyan1"),
RsgColor::Cyan2 => return String::from("cyan2"),
RsgColor::Cyan3 => return String::from("cyan3"),
RsgColor::Cyan4 => return String::from("cyan4"),
RsgColor::DarkBlue => return String::from("dark blue"),
RsgColor::DarkCyan => return String::from("dark cyan"),
RsgColor::DarkGoldenrod => return String::from("dark goldenrod"),
RsgColor::DarkGray => return String::from("dark gray"),
RsgColor::DarkGreen => return String::from("dark green"),
RsgColor::DarkGrey => return String::from("dark grey"),
RsgColor::DarkKhaki => return String::from("dark khaki"),
RsgColor::DarkMagenta => return String::from("dark magenta"),
RsgColor::DarkOliveGreen => return String::from("dark olive green"),
RsgColor::DarkOrange => return String::from("dark orange"),
RsgColor::DarkOrchid => return String::from("dark orchid"),
RsgColor::DarkRed => return String::from("dark red"),
RsgColor::DarkSalmon => return String::from("dark salmon"),
RsgColor::DarkSeaGreen => return String::from("dark sea green"),
RsgColor::DarkSlateBlue => return String::from("dark slate blue"),
RsgColor::DarkSlateGray => return String::from("dark slate gray"),
RsgColor::DarkSlateGrey => return String::from("dark slate grey"),
RsgColor::DarkTurquoise => return String::from("dark turquoise"),
RsgColor::DarkViolet => return String::from("dark violet"),
RsgColor::Darkblue => return String::from("DarkBlue"),
RsgColor::Darkcyan => return String::from("DarkCyan"),
RsgColor::Darkgoldenrod => return String::from("DarkGoldenrod"),
RsgColor::Darkgoldenrod1 => return String::from("DarkGoldenrod1"),
RsgColor::Darkgoldenrod2 => return String::from("DarkGoldenrod2"),
RsgColor::Darkgoldenrod3 => return String::from("DarkGoldenrod3"),
RsgColor::Darkgoldenrod4 => return String::from("DarkGoldenrod4"),
RsgColor::Darkgray => return String::from("DarkGray"),
RsgColor::Darkgreen => return String::from("DarkGreen"),
RsgColor::Darkgrey => return String::from("DarkGrey"),
RsgColor::Darkkhaki => return String::from("DarkKhaki"),
RsgColor::Darkmagenta => return String::from("DarkMagenta"),
RsgColor::Darkolivegreen => return String::from("DarkOliveGreen"),
RsgColor::Darkolivegreen1 => return String::from("DarkOliveGreen1"),
RsgColor::Darkolivegreen2 => return String::from("DarkOliveGreen2"),
RsgColor::Darkolivegreen3 => return String::from("DarkOliveGreen3"),
RsgColor::Darkolivegreen4 => return String::from("DarkOliveGreen4"),
RsgColor::Darkorange => return String::from("DarkOrange"),
RsgColor::Darkorange1 => return String::from("DarkOrange1"),
RsgColor::Darkorange2 => return String::from("DarkOrange2"),
RsgColor::Darkorange3 => return String::from("DarkOrange3"),
RsgColor::Darkorange4 => return String::from("DarkOrange4"),
RsgColor::Darkorchid => return String::from("DarkOrchid"),
RsgColor::Darkorchid1 => return String::from("DarkOrchid1"),
RsgColor::Darkorchid2 => return String::from("DarkOrchid2"),
RsgColor::Darkorchid3 => return String::from("DarkOrchid3"),
RsgColor::Darkorchid4 => return String::from("DarkOrchid4"),
RsgColor::Darkred => return String::from("DarkRed"),
RsgColor::Darksalmon => return String::from("DarkSalmon"),
RsgColor::Darkseagreen => return String::from("DarkSeaGreen"),
RsgColor::Darkseagreen1 => return String::from("DarkSeaGreen1"),
RsgColor::Darkseagreen2 => return String::from("DarkSeaGreen2"),
RsgColor::Darkseagreen3 => return String::from("DarkSeaGreen3"),
RsgColor::Darkseagreen4 => return String::from("DarkSeaGreen4"),
RsgColor::Darkslateblue => return String::from("DarkSlateBlue"),
RsgColor::Darkslategray => return String::from("DarkSlateGray"),
RsgColor::Darkslategray1 => return String::from("DarkSlateGray1"),
RsgColor::Darkslategray2 => return String::from("DarkSlateGray2"),
RsgColor::Darkslategray3 => return String::from("DarkSlateGray3"),
RsgColor::Darkslategray4 => return String::from("DarkSlateGray4"),
RsgColor::Darkslategrey => return String::from("DarkSlateGrey"),
RsgColor::Darkturquoise => return String::from("DarkTurquoise"),
RsgColor::Darkviolet => return String::from("DarkViolet"),
RsgColor::DeepPink => return String::from("deep pink"),
RsgColor::DeepSkyBlue => return String::from("deep sky blue"),
RsgColor::Deeppink => return String::from("DeepPink"),
RsgColor::Deeppink1 => return String::from("DeepPink1"),
RsgColor::Deeppink2 => return String::from("DeepPink2"),
RsgColor::Deeppink3 => return String::from("DeepPink3"),
RsgColor::Deeppink4 => return String::from("DeepPink4"),
RsgColor::Deepskyblue => return String::from("DeepSkyBlue"),
RsgColor::Deepskyblue1 => return String::from("DeepSkyBlue1"),
RsgColor::Deepskyblue2 => return String::from("DeepSkyBlue2"),
RsgColor::Deepskyblue3 => return String::from("DeepSkyBlue3"),
RsgColor::Deepskyblue4 => return String::from("DeepSkyBlue4"),
RsgColor::DimGray => return String::from("dim gray"),
RsgColor::DimGrey => return String::from("dim grey"),
RsgColor::Dimgray => return String::from("DimGray"),
RsgColor::Dimgrey => return String::from("DimGrey"),
RsgColor::DodgerBlue => return String::from("dodger blue"),
RsgColor::Dodgerblue => return String::from("DodgerBlue"),
RsgColor::Dodgerblue1 => return String::from("DodgerBlue1"),
RsgColor::Dodgerblue2 => return String::from("DodgerBlue2"),
RsgColor::Dodgerblue3 => return String::from("DodgerBlue3"),
RsgColor::Dodgerblue4 => return String::from("DodgerBlue4"),
RsgColor::Firebrick => return String::from("firebrick"),
RsgColor::Firebrick1 => return String::from("firebrick1"),
RsgColor::Firebrick2 => return String::from("firebrick2"),
RsgColor::Firebrick3 => return String::from("firebrick3"),
RsgColor::Firebrick4 => return String::from("firebrick4"),
RsgColor::FloralWhite => return String::from("floral white"),
RsgColor::Floralwhite => return String::from("FloralWhite"),
RsgColor::ForestGreen => return String::from("forest green"),
RsgColor::Forestgreen => return String::from("ForestGreen"),
RsgColor::Fuchsia => return String::from("fuchsia"),
RsgColor::Gainsboro => return String::from("gainsboro"),
RsgColor::GhostWhite => return String::from("ghost white"),
RsgColor::Ghostwhite => return String::from("GhostWhite"),
RsgColor::Gold => return String::from("gold"),
RsgColor::Gold1 => return String::from("gold1"),
RsgColor::Gold2 => return String::from("gold2"),
RsgColor::Gold3 => return String::from("gold3"),
RsgColor::Gold4 => return String::from("gold4"),
RsgColor::Goldenrod => return String::from("goldenrod"),
RsgColor::Goldenrod1 => return String::from("goldenrod1"),
RsgColor::Goldenrod2 => return String::from("goldenrod2"),
RsgColor::Goldenrod3 => return String::from("goldenrod3"),
RsgColor::Goldenrod4 => return String::from("goldenrod4"),
RsgColor::Gray => return String::from("gray"),
RsgColor::Gray0 => return String::from("gray0"),
RsgColor::Gray1 => return String::from("gray1"),
RsgColor::Gray2 => return String::from("gray2"),
RsgColor::Gray3 => return String::from("gray3"),
RsgColor::Gray4 => return String::from("gray4"),
RsgColor::Gray5 => return String::from("gray5"),
RsgColor::Gray6 => return String::from("gray6"),
RsgColor::Gray7 => return String::from("gray7"),
RsgColor::Gray8 => return String::from("gray8"),
RsgColor::Gray9 => return String::from("gray9"),
RsgColor::Gray10 => return String::from("gray10"),
RsgColor::Gray11 => return String::from("gray11"),
RsgColor::Gray12 => return String::from("gray12"),
RsgColor::Gray13 => return String::from("gray13"),
RsgColor::Gray14 => return String::from("gray14"),
RsgColor::Gray15 => return String::from("gray15"),
RsgColor::Gray16 => return String::from("gray16"),
RsgColor::Gray17 => return String::from("gray17"),
RsgColor::Gray18 => return String::from("gray18"),
RsgColor::Gray19 => return String::from("gray19"),
RsgColor::Gray20 => return String::from("gray20"),
RsgColor::Gray21 => return String::from("gray21"),
RsgColor::Gray22 => return String::from("gray22"),
RsgColor::Gray23 => return String::from("gray23"),
RsgColor::Gray24 => return String::from("gray24"),
RsgColor::Gray25 => return String::from("gray25"),
RsgColor::Gray26 => return String::from("gray26"),
RsgColor::Gray27 => return String::from("gray27"),
RsgColor::Gray28 => return String::from("gray28"),
RsgColor::Gray29 => return String::from("gray29"),
RsgColor::Gray30 => return String::from("gray30"),
RsgColor::Gray31 => return String::from("gray31"),
RsgColor::Gray32 => return String::from("gray32"),
RsgColor::Gray33 => return String::from("gray33"),
RsgColor::Gray34 => return String::from("gray34"),
RsgColor::Gray35 => return String::from("gray35"),
RsgColor::Gray36 => return String::from("gray36"),
RsgColor::Gray37 => return String::from("gray37"),
RsgColor::Gray38 => return String::from("gray38"),
RsgColor::Gray39 => return String::from("gray39"),
RsgColor::Gray40 => return String::from("gray40"),
RsgColor::Gray41 => return String::from("gray41"),
RsgColor::Gray42 => return String::from("gray42"),
RsgColor::Gray43 => return String::from("gray43"),
RsgColor::Gray44 => return String::from("gray44"),
RsgColor::Gray45 => return String::from("gray45"),
RsgColor::Gray46 => return String::from("gray46"),
RsgColor::Gray47 => return String::from("gray47"),
RsgColor::Gray48 => return String::from("gray48"),
RsgColor::Gray49 => return String::from("gray49"),
RsgColor::Gray50 => return String::from("gray50"),
RsgColor::Gray51 => return String::from("gray51"),
RsgColor::Gray52 => return String::from("gray52"),
RsgColor::Gray53 => return String::from("gray53"),
RsgColor::Gray54 => return String::from("gray54"),
RsgColor::Gray55 => return String::from("gray55"),
RsgColor::Gray56 => return String::from("gray56"),
RsgColor::Gray57 => return String::from("gray57"),
RsgColor::Gray58 => return String::from("gray58"),
RsgColor::Gray59 => return String::from("gray59"),
RsgColor::Gray60 => return String::from("gray60"),
RsgColor::Gray61 => return String::from("gray61"),
RsgColor::Gray62 => return String::from("gray62"),
RsgColor::Gray63 => return String::from("gray63"),
RsgColor::Gray64 => return String::from("gray64"),
RsgColor::Gray65 => return String::from("gray65"),
RsgColor::Gray66 => return String::from("gray66"),
RsgColor::Gray67 => return String::from("gray67"),
RsgColor::Gray68 => return String::from("gray68"),
RsgColor::Gray69 => return String::from("gray69"),
RsgColor::Gray70 => return String::from("gray70"),
RsgColor::Gray71 => return String::from("gray71"),
RsgColor::Gray72 => return String::from("gray72"),
RsgColor::Gray73 => return String::from("gray73"),
RsgColor::Gray74 => return String::from("gray74"),
RsgColor::Gray75 => return String::from("gray75"),
RsgColor::Gray76 => return String::from("gray76"),
RsgColor::Gray77 => return String::from("gray77"),
RsgColor::Gray78 => return String::from("gray78"),
RsgColor::Gray79 => return String::from("gray79"),
RsgColor::Gray80 => return String::from("gray80"),
RsgColor::Gray81 => return String::from("gray81"),
RsgColor::Gray82 => return String::from("gray82"),
RsgColor::Gray83 => return String::from("gray83"),
RsgColor::Gray84 => return String::from("gray84"),
RsgColor::Gray85 => return String::from("gray85"),
RsgColor::Gray86 => return String::from("gray86"),
RsgColor::Gray87 => return String::from("gray87"),
RsgColor::Gray88 => return String::from("gray88"),
RsgColor::Gray89 => return String::from("gray89"),
RsgColor::Gray90 => return String::from("gray90"),
RsgColor::Gray91 => return String::from("gray91"),
RsgColor::Gray92 => return String::from("gray92"),
RsgColor::Gray93 => return String::from("gray93"),
RsgColor::Gray94 => return String::from("gray94"),
RsgColor::Gray95 => return String::from("gray95"),
RsgColor::Gray96 => return String::from("gray96"),
RsgColor::Gray97 => return String::from("gray97"),
RsgColor::Gray98 => return String::from("gray98"),
RsgColor::Gray99 => return String::from("gray99"),
RsgColor::Gray100 => return String::from("gray100"),
RsgColor::Green => return String::from("green"),
RsgColor::GreenYellow => return String::from("green yellow"),
RsgColor::Green1 => return String::from("green1"),
RsgColor::Green2 => return String::from("green2"),
RsgColor::Green3 => return String::from("green3"),
RsgColor::Green4 => return String::from("green4"),
RsgColor::Greenyellow => return String::from("GreenYellow"),
RsgColor::Grey => return String::from("grey"),
RsgColor::Grey0 => return String::from("grey0"),
RsgColor::Grey1 => return String::from("grey1"),
RsgColor::Grey2 => return String::from("grey2"),
RsgColor::Grey3 => return String::from("grey3"),
RsgColor::Grey4 => return String::from("grey4"),
RsgColor::Grey5 => return String::from("grey5"),
RsgColor::Grey6 => return String::from("grey6"),
RsgColor::Grey7 => return String::from("grey7"),
RsgColor::Grey8 => return String::from("grey8"),
RsgColor::Grey9 => return String::from("grey9"),
RsgColor::Grey10 => return String::from("grey10"),
RsgColor::Grey11 => return String::from("grey11"),
RsgColor::Grey12 => return String::from("grey12"),
RsgColor::Grey13 => return String::from("grey13"),
RsgColor::Grey14 => return String::from("grey14"),
RsgColor::Grey15 => return String::from("grey15"),
RsgColor::Grey16 => return String::from("grey16"),
RsgColor::Grey17 => return String::from("grey17"),
RsgColor::Grey18 => return String::from("grey18"),
RsgColor::Grey19 => return String::from("grey19"),
RsgColor::Grey20 => return String::from("grey20"),
RsgColor::Grey21 => return String::from("grey21"),
RsgColor::Grey22 => return String::from("grey22"),
RsgColor::Grey23 => return String::from("grey23"),
RsgColor::Grey24 => return String::from("grey24"),
RsgColor::Grey25 => return String::from("grey25"),
RsgColor::Grey26 => return String::from("grey26"),
RsgColor::Grey27 => return String::from("grey27"),
RsgColor::Grey28 => return String::from("grey28"),
RsgColor::Grey29 => return String::from("grey29"),
RsgColor::Grey30 => return String::from("grey30"),
RsgColor::Grey31 => return String::from("grey31"),
RsgColor::Grey32 => return String::from("grey32"),
RsgColor::Grey33 => return String::from("grey33"),
RsgColor::Grey34 => return String::from("grey34"),
RsgColor::Grey35 => return String::from("grey35"),
RsgColor::Grey36 => return String::from("grey36"),
RsgColor::Grey37 => return String::from("grey37"),
RsgColor::Grey38 => return String::from("grey38"),
RsgColor::Grey39 => return String::from("grey39"),
RsgColor::Grey40 => return String::from("grey40"),
RsgColor::Grey41 => return String::from("grey41"),
RsgColor::Grey42 => return String::from("grey42"),
RsgColor::Grey43 => return String::from("grey43"),
RsgColor::Grey44 => return String::from("grey44"),
RsgColor::Grey45 => return String::from("grey45"),
RsgColor::Grey46 => return String::from("grey46"),
RsgColor::Grey47 => return String::from("grey47"),
RsgColor::Grey48 => return String::from("grey48"),
RsgColor::Grey49 => return String::from("grey49"),
RsgColor::Grey50 => return String::from("grey50"),
RsgColor::Grey51 => return String::from("grey51"),
RsgColor::Grey52 => return String::from("grey52"),
RsgColor::Grey53 => return String::from("grey53"),
RsgColor::Grey54 => return String::from("grey54"),
RsgColor::Grey55 => return String::from("grey55"),
RsgColor::Grey56 => return String::from("grey56"),
RsgColor::Grey57 => return String::from("grey57"),
RsgColor::Grey58 => return String::from("grey58"),
RsgColor::Grey59 => return String::from("grey59"),
RsgColor::Grey60 => return String::from("grey60"),
RsgColor::Grey61 => return String::from("grey61"),
RsgColor::Grey62 => return String::from("grey62"),
RsgColor::Grey63 => return String::from("grey63"),
RsgColor::Grey64 => return String::from("grey64"),
RsgColor::Grey65 => return String::from("grey65"),
RsgColor::Grey66 => return String::from("grey66"),
RsgColor::Grey67 => return String::from("grey67"),
RsgColor::Grey68 => return String::from("grey68"),
RsgColor::Grey69 => return String::from("grey69"),
RsgColor::Grey70 => return String::from("grey70"),
RsgColor::Grey71 => return String::from("grey71"),
RsgColor::Grey72 => return String::from("grey72"),
RsgColor::Grey73 => return String::from("grey73"),
RsgColor::Grey74 => return String::from("grey74"),
RsgColor::Grey75 => return String::from("grey75"),
RsgColor::Grey76 => return String::from("grey76"),
RsgColor::Grey77 => return String::from("grey77"),
RsgColor::Grey78 => return String::from("grey78"),
RsgColor::Grey79 => return String::from("grey79"),
RsgColor::Grey80 => return String::from("grey80"),
RsgColor::Grey81 => return String::from("grey81"),
RsgColor::Grey82 => return String::from("grey82"),
RsgColor::Grey83 => return String::from("grey83"),
RsgColor::Grey84 => return String::from("grey84"),
RsgColor::Grey85 => return String::from("grey85"),
RsgColor::Grey86 => return String::from("grey86"),
RsgColor::Grey87 => return String::from("grey87"),
RsgColor::Grey88 => return String::from("grey88"),
RsgColor::Grey89 => return String::from("grey89"),
RsgColor::Grey90 => return String::from("grey90"),
RsgColor::Grey91 => return String::from("grey91"),
RsgColor::Grey92 => return String::from("grey92"),
RsgColor::Grey93 => return String::from("grey93"),
RsgColor::Grey94 => return String::from("grey94"),
RsgColor::Grey95 => return String::from("grey95"),
RsgColor::Grey96 => return String::from("grey96"),
RsgColor::Grey97 => return String::from("grey97"),
RsgColor::Grey98 => return String::from("grey98"),
RsgColor::Grey99 => return String::from("grey99"),
RsgColor::Grey100 => return String::from("grey100"),
RsgColor::Honeydew => return String::from("honeydew"),
RsgColor::Honeydew1 => return String::from("honeydew1"),
RsgColor::Honeydew2 => return String::from("honeydew2"),
RsgColor::Honeydew3 => return String::from("honeydew3"),
RsgColor::Honeydew4 => return String::from("honeydew4"),
RsgColor::HotPink => return String::from("hot pink"),
RsgColor::Hotpink => return String::from("HotPink"),
RsgColor::Hotpink1 => return String::from("HotPink1"),
RsgColor::Hotpink2 => return String::from("HotPink2"),
RsgColor::Hotpink3 => return String::from("HotPink3"),
RsgColor::Hotpink4 => return String::from("HotPink4"),
RsgColor::IndianRed => return String::from("indian red"),
RsgColor::Indianred => return String::from("IndianRed"),
RsgColor::Indianred1 => return String::from("IndianRed1"),
RsgColor::Indianred2 => return String::from("IndianRed2"),
RsgColor::Indianred3 => return String::from("IndianRed3"),
RsgColor::Indianred4 => return String::from("IndianRed4"),
RsgColor::Indigo => return String::from("indigo"),
RsgColor::Ivory => return String::from("ivory"),
RsgColor::Ivory1 => return String::from("ivory1"),
RsgColor::Ivory2 => return String::from("ivory2"),
RsgColor::Ivory3 => return String::from("ivory3"),
RsgColor::Ivory4 => return String::from("ivory4"),
RsgColor::Khaki => return String::from("khaki"),
RsgColor::Khaki1 => return String::from("khaki1"),
RsgColor::Khaki2 => return String::from("khaki2"),
RsgColor::Khaki3 => return String::from("khaki3"),
RsgColor::Khaki4 => return String::from("khaki4"),
RsgColor::Lavender => return String::from("lavender"),
RsgColor::LavenderBlush => return String::from("lavender blush"),
RsgColor::Lavenderblush => return String::from("LavenderBlush"),
RsgColor::Lavenderblush1 => return String::from("LavenderBlush1"),
RsgColor::Lavenderblush2 => return String::from("LavenderBlush2"),
RsgColor::Lavenderblush3 => return String::from("LavenderBlush3"),
RsgColor::Lavenderblush4 => return String::from("LavenderBlush4"),
RsgColor::LawnGreen => return String::from("lawn green"),
RsgColor::Lawngreen => return String::from("LawnGreen"),
RsgColor::LemonChiffon => return String::from("lemon chiffon"),
RsgColor::Lemonchiffon => return String::from("LemonChiffon"),
RsgColor::Lemonchiffon1 => return String::from("LemonChiffon1"),
RsgColor::Lemonchiffon2 => return String::from("LemonChiffon2"),
RsgColor::Lemonchiffon3 => return String::from("LemonChiffon3"),
RsgColor::Lemonchiffon4 => return String::from("LemonChiffon4"),
RsgColor::LightBlue => return String::from("light blue"),
RsgColor::LightCoral => return String::from("light coral"),
RsgColor::LightCyan => return String::from("light cyan"),
RsgColor::LightGoldenrod => return String::from("light goldenrod"),
RsgColor::LightGoldenrodYellow => return String::from("light goldenrod yellow"),
RsgColor::LightGray => return String::from("light gray"),
RsgColor::LightGreen => return String::from("light green"),
RsgColor::LightGrey => return String::from("light grey"),
RsgColor::LightPink => return String::from("light pink"),
RsgColor::LightSalmon => return String::from("light salmon"),
RsgColor::LightSeaGreen => return String::from("light sea green"),
RsgColor::LightSkyBlue => return String::from("light sky blue"),
RsgColor::LightSlateBlue => return String::from("light slate blue"),
RsgColor::LightSlateGray => return String::from("light slate gray"),
RsgColor::LightSlateGrey => return String::from("light slate grey"),
RsgColor::LightSteelBlue => return String::from("light steel blue"),
RsgColor::LightYellow => return String::from("light yellow"),
RsgColor::Lightblue => return String::from("LightBlue"),
RsgColor::Lightblue1 => return String::from("LightBlue1"),
RsgColor::Lightblue2 => return String::from("LightBlue2"),
RsgColor::Lightblue3 => return String::from("LightBlue3"),
RsgColor::Lightblue4 => return String::from("LightBlue4"),
RsgColor::Lightcoral => return String::from("LightCoral"),
RsgColor::Lightcyan => return String::from("LightCyan"),
RsgColor::Lightcyan1 => return String::from("LightCyan1"),
RsgColor::Lightcyan2 => return String::from("LightCyan2"),
RsgColor::Lightcyan3 => return String::from("LightCyan3"),
RsgColor::Lightcyan4 => return String::from("LightCyan4"),
RsgColor::Lightgoldenrod => return String::from("LightGoldenrod"),
RsgColor::Lightgoldenrod1 => return String::from("LightGoldenrod1"),
RsgColor::Lightgoldenrod2 => return String::from("LightGoldenrod2"),
RsgColor::Lightgoldenrod3 => return String::from("LightGoldenrod3"),
RsgColor::Lightgoldenrod4 => return String::from("LightGoldenrod4"),
RsgColor::Lightgoldenrodyellow => return String::from("LightGoldenrodYellow"),
RsgColor::Lightgray => return String::from("LightGray"),
RsgColor::Lightgreen => return String::from("LightGreen"),
RsgColor::Lightgrey => return String::from("LightGrey"),
RsgColor::Lightpink => return String::from("LightPink"),
RsgColor::Lightpink1 => return String::from("LightPink1"),
RsgColor::Lightpink2 => return String::from("LightPink2"),
RsgColor::Lightpink3 => return String::from("LightPink3"),
RsgColor::Lightpink4 => return String::from("LightPink4"),
RsgColor::Lightsalmon => return String::from("LightSalmon"),
RsgColor::Lightsalmon1 => return String::from("LightSalmon1"),
RsgColor::Lightsalmon2 => return String::from("LightSalmon2"),
RsgColor::Lightsalmon3 => return String::from("LightSalmon3"),
RsgColor::Lightsalmon4 => return String::from("LightSalmon4"),
RsgColor::Lightseagreen => return String::from("LightSeaGreen"),
RsgColor::Lightskyblue => return String::from("LightSkyBlue"),
RsgColor::Lightskyblue1 => return String::from("LightSkyBlue1"),
RsgColor::Lightskyblue2 => return String::from("LightSkyBlue2"),
RsgColor::Lightskyblue3 => return String::from("LightSkyBlue3"),
RsgColor::Lightskyblue4 => return String::from("LightSkyBlue4"),
RsgColor::Lightslateblue => return String::from("LightSlateBlue"),
RsgColor::Lightslategray => return String::from("LightSlateGray"),
RsgColor::Lightslategrey => return String::from("LightSlateGrey"),
RsgColor::Lightsteelblue => return String::from("LightSteelBlue"),
RsgColor::Lightsteelblue1 => return String::from("LightSteelBlue1"),
RsgColor::Lightsteelblue2 => return String::from("LightSteelBlue2"),
RsgColor::Lightsteelblue3 => return String::from("LightSteelBlue3"),
RsgColor::Lightsteelblue4 => return String::from("LightSteelBlue4"),
RsgColor::Lightyellow => return String::from("LightYellow"),
RsgColor::Lightyellow1 => return String::from("LightYellow1"),
RsgColor::Lightyellow2 => return String::from("LightYellow2"),
RsgColor::Lightyellow3 => return String::from("LightYellow3"),
RsgColor::Lightyellow4 => return String::from("LightYellow4"),
RsgColor::Lime => return String::from("lime"),
RsgColor::LimeGreen => return String::from("lime green"),
RsgColor::Limegreen => return String::from("LimeGreen"),
RsgColor::Linen => return String::from("linen"),
RsgColor::Magenta => return String::from("magenta"),
RsgColor::Magenta1 => return String::from("magenta1"),
RsgColor::Magenta2 => return String::from("magenta2"),
RsgColor::Magenta3 => return String::from("magenta3"),
RsgColor::Magenta4 => return String::from("magenta4"),
RsgColor::Maroon => return String::from("maroon"),
RsgColor::Maroon1 => return String::from("maroon1"),
RsgColor::Maroon2 => return String::from("maroon2"),
RsgColor::Maroon3 => return String::from("maroon3"),
RsgColor::Maroon4 => return String::from("maroon4"),
RsgColor::MediumAquamarine => return String::from("medium aquamarine"),
RsgColor::MediumBlue => return String::from("medium blue"),
RsgColor::MediumOrchid => return String::from("medium orchid"),
RsgColor::MediumPurple => return String::from("medium purple"),
RsgColor::MediumSeaGreen => return String::from("medium sea green"),
RsgColor::MediumSlateBlue => return String::from("medium slate blue"),
RsgColor::MediumSpringGreen => return String::from("medium spring green"),
RsgColor::MediumTurquoise => return String::from("medium turquoise"),
RsgColor::MediumVioletRed => return String::from("medium violet red"),
RsgColor::Mediumaquamarine => return String::from("MediumAquamarine"),
RsgColor::Mediumblue => return String::from("MediumBlue"),
RsgColor::Mediumorchid => return String::from("MediumOrchid"),
RsgColor::Mediumorchid1 => return String::from("MediumOrchid1"),
RsgColor::Mediumorchid2 => return String::from("MediumOrchid2"),
RsgColor::Mediumorchid3 => return String::from("MediumOrchid3"),
RsgColor::Mediumorchid4 => return String::from("MediumOrchid4"),
RsgColor::Mediumpurple => return String::from("MediumPurple"),
RsgColor::Mediumpurple1 => return String::from("MediumPurple1"),
RsgColor::Mediumpurple2 => return String::from("MediumPurple2"),
RsgColor::Mediumpurple3 => return String::from("MediumPurple3"),
RsgColor::Mediumpurple4 => return String::from("MediumPurple4"),
RsgColor::Mediumseagreen => return String::from("MediumSeaGreen"),
RsgColor::Mediumslateblue => return String::from("MediumSlateBlue"),
RsgColor::Mediumspringgreen => return String::from("MediumSpringGreen"),
RsgColor::Mediumturquoise => return String::from("MediumTurquoise"),
RsgColor::Mediumvioletred => return String::from("MediumVioletRed"),
RsgColor::MidnightBlue => return String::from("midnight blue"),
RsgColor::Midnightblue => return String::from("MidnightBlue"),
RsgColor::MintCream => return String::from("mint cream"),
RsgColor::Mintcream => return String::from("MintCream"),
RsgColor::MistyRose => return String::from("misty rose"),
RsgColor::Mistyrose => return String::from("MistyRose"),
RsgColor::Mistyrose1 => return String::from("MistyRose1"),
RsgColor::Mistyrose2 => return String::from("MistyRose2"),
RsgColor::Mistyrose3 => return String::from("MistyRose3"),
RsgColor::Mistyrose4 => return String::from("MistyRose4"),
RsgColor::Moccasin => return String::from("moccasin"),
RsgColor::NavajoWhite => return String::from("navajo white"),
RsgColor::Navajowhite => return String::from("NavajoWhite"),
RsgColor::Navajowhite1 => return String::from("NavajoWhite1"),
RsgColor::Navajowhite2 => return String::from("NavajoWhite2"),
RsgColor::Navajowhite3 => return String::from("NavajoWhite3"),
RsgColor::Navajowhite4 => return String::from("NavajoWhite4"),
RsgColor::Navy => return String::from("navy"),
RsgColor::NavyBlue => return String::from("navy blue"),
RsgColor::Navyblue => return String::from("NavyBlue"),
RsgColor::OldLace => return String::from("old lace"),
RsgColor::Oldlace => return String::from("OldLace"),
RsgColor::Olive => return String::from("olive"),
RsgColor::OliveDrab => return String::from("olive drab"),
RsgColor::Olivedrab => return String::from("OliveDrab"),
RsgColor::Olivedrab1 => return String::from("OliveDrab1"),
RsgColor::Olivedrab2 => return String::from("OliveDrab2"),
RsgColor::Olivedrab3 => return String::from("OliveDrab3"),
RsgColor::Olivedrab4 => return String::from("OliveDrab4"),
RsgColor::Orange => return String::from("orange"),
RsgColor::OrangeRed => return String::from("orange red"),
RsgColor::Orange1 => return String::from("orange1"),
RsgColor::Orange2 => return String::from("orange2"),
RsgColor::Orange3 => return String::from("orange3"),
RsgColor::Orange4 => return String::from("orange4"),
RsgColor::Orangered => return String::from("OrangeRed"),
RsgColor::Orangered1 => return String::from("OrangeRed1"),
RsgColor::Orangered2 => return String::from("OrangeRed2"),
RsgColor::Orangered3 => return String::from("OrangeRed3"),
RsgColor::Orangered4 => return String::from("OrangeRed4"),
RsgColor::Orchid => return String::from("orchid"),
RsgColor::Orchid1 => return String::from("orchid1"),
RsgColor::Orchid2 => return String::from("orchid2"),
RsgColor::Orchid3 => return String::from("orchid3"),
RsgColor::Orchid4 => return String::from("orchid4"),
RsgColor::PaleGoldenrod => return String::from("pale goldenrod"),
RsgColor::PaleGreen => return String::from("pale green"),
RsgColor::PaleTurquoise => return String::from("pale turquoise"),
RsgColor::PaleVioletRed => return String::from("pale violet red"),
RsgColor::Palegoldenrod => return String::from("PaleGoldenrod"),
RsgColor::Palegreen => return String::from("PaleGreen"),
RsgColor::Palegreen1 => return String::from("PaleGreen1"),
RsgColor::Palegreen2 => return String::from("PaleGreen2"),
RsgColor::Palegreen3 => return String::from("PaleGreen3"),
RsgColor::Palegreen4 => return String::from("PaleGreen4"),
RsgColor::Paleturquoise => return String::from("PaleTurquoise"),
RsgColor::Paleturquoise1 => return String::from("PaleTurquoise1"),
RsgColor::Paleturquoise2 => return String::from("PaleTurquoise2"),
RsgColor::Paleturquoise3 => return String::from("PaleTurquoise3"),
RsgColor::Paleturquoise4 => return String::from("PaleTurquoise4"),
RsgColor::Palevioletred => return String::from("PaleVioletRed"),
RsgColor::Palevioletred1 => return String::from("PaleVioletRed1"),
RsgColor::Palevioletred2 => return String::from("PaleVioletRed2"),
RsgColor::Palevioletred3 => return String::from("PaleVioletRed3"),
RsgColor::Palevioletred4 => return String::from("PaleVioletRed4"),
RsgColor::PapayaWhip => return String::from("papaya whip"),
RsgColor::Papayawhip => return String::from("PapayaWhip"),
RsgColor::PeachPuff => return String::from("peach puff"),
RsgColor::Peachpuff => return String::from("PeachPuff"),
RsgColor::Peachpuff1 => return String::from("PeachPuff1"),
RsgColor::Peachpuff2 => return String::from("PeachPuff2"),
RsgColor::Peachpuff3 => return String::from("PeachPuff3"),
RsgColor::Peachpuff4 => return String::from("PeachPuff4"),
RsgColor::Peru => return String::from("peru"),
RsgColor::Pink => return String::from("pink"),
RsgColor::Pink1 => return String::from("pink1"),
RsgColor::Pink2 => return String::from("pink2"),
RsgColor::Pink3 => return String::from("pink3"),
RsgColor::Pink4 => return String::from("pink4"),
RsgColor::Plum => return String::from("plum"),
RsgColor::Plum1 => return String::from("plum1"),
RsgColor::Plum2 => return String::from("plum2"),
RsgColor::Plum3 => return String::from("plum3"),
RsgColor::Plum4 => return String::from("plum4"),
RsgColor::PowderBlue => return String::from("powder blue"),
RsgColor::Powderblue => return String::from("PowderBlue"),
RsgColor::Purple => return String::from("purple"),
RsgColor::Purple1 => return String::from("purple1"),
RsgColor::Purple2 => return String::from("purple2"),
RsgColor::Purple3 => return String::from("purple3"),
RsgColor::Purple4 => return String::from("purple4"),
RsgColor::Red => return String::from("red"),
RsgColor::Red1 => return String::from("red1"),
RsgColor::Red2 => return String::from("red2"),
RsgColor::Red3 => return String::from("red3"),
RsgColor::Red4 => return String::from("red4"),
RsgColor::RosyBrown => return String::from("rosy brown"),
RsgColor::Rosybrown => return String::from("RosyBrown"),
RsgColor::Rosybrown1 => return String::from("RosyBrown1"),
RsgColor::Rosybrown2 => return String::from("RosyBrown2"),
RsgColor::Rosybrown3 => return String::from("RosyBrown3"),
RsgColor::Rosybrown4 => return String::from("RosyBrown4"),
RsgColor::RoyalBlue => return String::from("royal blue"),
RsgColor::Royalblue => return String::from("RoyalBlue"),
RsgColor::Royalblue1 => return String::from("RoyalBlue1"),
RsgColor::Royalblue2 => return String::from("RoyalBlue2"),
RsgColor::Royalblue3 => return String::from("RoyalBlue3"),
RsgColor::Royalblue4 => return String::from("RoyalBlue4"),
RsgColor::SaddleBrown => return String::from("saddle brown"),
RsgColor::Saddlebrown => return String::from("SaddleBrown"),
RsgColor::Salmon => return String::from("salmon"),
RsgColor::Salmon1 => return String::from("salmon1"),
RsgColor::Salmon2 => return String::from("salmon2"),
RsgColor::Salmon3 => return String::from("salmon3"),
RsgColor::Salmon4 => return String::from("salmon4"),
RsgColor::SandyBrown => return String::from("sandy brown"),
RsgColor::Sandybrown => return String::from("SandyBrown"),
RsgColor::SeaGreen => return String::from("sea green"),
RsgColor::Seagreen => return String::from("SeaGreen"),
RsgColor::Seagreen1 => return String::from("SeaGreen1"),
RsgColor::Seagreen2 => return String::from("SeaGreen2"),
RsgColor::Seagreen3 => return String::from("SeaGreen3"),
RsgColor::Seagreen4 => return String::from("SeaGreen4"),
RsgColor::Seashell => return String::from("seashell"),
RsgColor::Seashell1 => return String::from("seashell1"),
RsgColor::Seashell2 => return String::from("seashell2"),
RsgColor::Seashell3 => return String::from("seashell3"),
RsgColor::Seashell4 => return String::from("seashell4"),
RsgColor::Sienna => return String::from("sienna"),
RsgColor::Sienna1 => return String::from("sienna1"),
RsgColor::Sienna2 => return String::from("sienna2"),
RsgColor::Sienna3 => return String::from("sienna3"),
RsgColor::Sienna4 => return String::from("sienna4"),
RsgColor::Silver => return String::from("silver"),
RsgColor::SkyBlue => return String::from("sky blue"),
RsgColor::Skyblue => return String::from("SkyBlue"),
RsgColor::Skyblue1 => return String::from("SkyBlue1"),
RsgColor::Skyblue2 => return String::from("SkyBlue2"),
RsgColor::Skyblue3 => return String::from("SkyBlue3"),
RsgColor::Skyblue4 => return String::from("SkyBlue4"),
RsgColor::SlateBlue => return String::from("slate blue"),
RsgColor::SlateGray => return String::from("slate gray"),
RsgColor::SlateGrey => return String::from("slate grey"),
RsgColor::Slateblue => return String::from("SlateBlue"),
RsgColor::Slateblue1 => return String::from("SlateBlue1"),
RsgColor::Slateblue2 => return String::from("SlateBlue2"),
RsgColor::Slateblue3 => return String::from("SlateBlue3"),
RsgColor::Slateblue4 => return String::from("SlateBlue4"),
RsgColor::Slategray => return String::from("SlateGray"),
RsgColor::Slategray1 => return String::from("SlateGray1"),
RsgColor::Slategray2 => return String::from("SlateGray2"),
RsgColor::Slategray3 => return String::from("SlateGray3"),
RsgColor::Slategray4 => return String::from("SlateGray4"),
RsgColor::Slategrey => return String::from("SlateGrey"),
RsgColor::Snow => return String::from("snow"),
RsgColor::Snow1 => return String::from("snow1"),
RsgColor::Snow2 => return String::from("snow2"),
RsgColor::Snow3 => return String::from("snow3"),
RsgColor::Snow4 => return String::from("snow4"),
RsgColor::SpringGreen => return String::from("spring green"),
RsgColor::Springgreen => return String::from("SpringGreen"),
RsgColor::Springgreen1 => return String::from("SpringGreen1"),
RsgColor::Springgreen2 => return String::from("SpringGreen2"),
RsgColor::Springgreen3 => return String::from("SpringGreen3"),
RsgColor::Springgreen4 => return String::from("SpringGreen4"),
RsgColor::SteelBlue => return String::from("steel blue"),
RsgColor::Steelblue => return String::from("SteelBlue"),
RsgColor::Steelblue1 => return String::from("SteelBlue1"),
RsgColor::Steelblue2 => return String::from("SteelBlue2"),
RsgColor::Steelblue3 => return String::from("SteelBlue3"),
RsgColor::Steelblue4 => return String::from("SteelBlue4"),
RsgColor::Tan => return String::from("tan"),
RsgColor::Tan1 => return String::from("tan1"),
RsgColor::Tan2 => return String::from("tan2"),
RsgColor::Tan3 => return String::from("tan3"),
RsgColor::Tan4 => return String::from("tan4"),
RsgColor::Teal => return String::from("teal"),
RsgColor::Thistle => return String::from("thistle"),
RsgColor::Thistle1 => return String::from("thistle1"),
RsgColor::Thistle2 => return String::from("thistle2"),
RsgColor::Thistle3 => return String::from("thistle3"),
RsgColor::Thistle4 => return String::from("thistle4"),
RsgColor::Tomato => return String::from("tomato"),
RsgColor::Tomato1 => return String::from("tomato1"),
RsgColor::Tomato2 => return String::from("tomato2"),
RsgColor::Tomato3 => return String::from("tomato3"),
RsgColor::Tomato4 => return String::from("tomato4"),
RsgColor::Turquoise => return String::from("turquoise"),
RsgColor::Turquoise1 => return String::from("turquoise1"),
RsgColor::Turquoise2 => return String::from("turquoise2"),
RsgColor::Turquoise3 => return String::from("turquoise3"),
RsgColor::Turquoise4 => return String::from("turquoise4"),
RsgColor::Violet => return String::from("violet"),
RsgColor::VioletRed => return String::from("violet red"),
RsgColor::Violetred => return String::from("VioletRed"),
RsgColor::Violetred1 => return String::from("VioletRed1"),
RsgColor::Violetred2 => return String::from("VioletRed2"),
RsgColor::Violetred3 => return String::from("VioletRed3"),
RsgColor::Violetred4 => return String::from("VioletRed4"),
RsgColor::Wheat => return String::from("wheat"),
RsgColor::Wheat1 => return String::from("wheat1"),
RsgColor::Wheat2 => return String::from("wheat2"),
RsgColor::Wheat3 => return String::from("wheat3"),
RsgColor::Wheat4 => return String::from("wheat4"),
RsgColor::White => return String::from("white"),
RsgColor::WhiteSmoke => return String::from("white smoke"),
RsgColor::Whitesmoke => return String::from("WhiteSmoke"),
RsgColor::Yellow => return String::from("yellow"),
RsgColor::YellowGreen => return String::from("yellow green"),
RsgColor::Yellow1 => return String::from("yellow1"),
RsgColor::Yellow2 => return String::from("yellow2"),
RsgColor::Yellow3 => return String::from("yellow3"),
RsgColor::Yellow4 => return String::from("yellow4"),
RsgColor::Yellowgreen => return String::from("YellowGreen"),
        _ => {}
    }
    return "".to_string()
}