[package]
name = "rustsimplegui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rsg_tk = { path = "../rsg_tk" }


[features]
rsg_tk = []
rsg_relm4 = []


